baseurl: "/klantinteracties"
apiname: "Standaard voor Klantinteracties"
url: "http://localhost:4000"
# nav is t.b.v. generatie side-navigation menu.
# Een 'title' zonder path of url genereert slechts een kopje.
# 'path' vormt tezamen met de baseurl de url waarmee de 'href' wordt gevuld.
# Indien een 'url' voorradig dan wordt daarmee de 'href' gevuld en dient het path slechts om te bepalen welke link active is.
# 'target: blank' zorgt er voor dat de link in een nieuw tabblad wordt geopend.
nav:
  - title: Klantinteracties
    subnav:
      - title: Home
        path: /
      - title: Productvisie
        path: /productvisie
#     - title: Quickstart
#       path: /quickstart
#     - title: Architectuur
#       path: /architectuur
  - title: Informatiemodel
    subnav:
#      - title: Basisterminologie
#        path: /informatiemodel/basisterminologie
      - title: Semantisch model (SIM)
        path: /informatiemodel/semantisch_model
#      - title: Uitwisselingsmodel (UGM)
#        path: /informatiemodel/uitwisselingsmodel
      - title: Gegevenswoordenboek
        path: /informatiemodel/gegevenswoordenboek
  - title: API-familie Partij
    subnav:
      - title: Ontwerpvarianten specificaties
        path: /api_familie_x/varianten
#      - title: Gedragsspecificaties
#        path: /api_familie_x/gedragsspecificaties
#      - title: Referentieimplementatie
#        path: /api_familie_x/referentieimplementatie
  - title: Achtergrond documentatie
    subnav: 
      - title: Uitgangspunten
        path: /achtergronddocumentatie/uitgangspunten
      - title: Cases
        path: /achtergronddocumentatie/cases
      - title: Functies
        path: /achtergronddocumentatie/functies
      - title: Vragen en besluiten
        path: /achtergronddocumentatie/Vragen en besluiten    
  - title: Vraag en Antwoord
    subnav:
#      - title: Veelgestelde vragen
#        path: /veelgesteldevragen
      - title: Contact 
        path: /contact
    subnav:
      - title: Markdown test
        path: /test/markdown-layout

plugins:
  - jekyll-redirect-from
  - jekyll-remote-theme
  - jemoji

github: hdksi/klantinteracties

#theme: jekyll-theme-time-machine

remote_theme: https://github.com/hdksi/jekyll-theme-vng-realisatie

project_name: Standaard voor Klantinteracties

standard_family: nvt

markdown: kramdown

lsi: false
safe: true
source: [your repo's top level directory]
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# More › http://kramdown.gettalong.org/quickref.html
# Options › http://kramdown.gettalong.org/options.html
#kramdown:
  #input: GFM
  # https://github.com/jekyll/jekyll/pull/4090
  #syntax_highlighter: rouge

  # Rouge Highlighter in Kramdown › http://kramdown.gettalong.org/syntax_highlighter/rouge.html
  # span, block element options fall back to global
  #syntax_highlighter_opts:
    # Rouge Options › https://github.com/jneen/rouge#full-options
    #css_class: 'highlight'
    #line_numbers: true # bad idea, spans don't need linenos and would inherit this option
    #span:
      #line_numbers: false
    #block:
      #line_numbers: true
      #start_line: 1
